### ISSUE TITLE
!mockType is non-standard JSDoc tag (exclamation mark)

### ISSUE THREAD

**Issue by hasparus** [google/intermock#10]
Hi @ryanmcdermott 👋

I wanted to ask about the exclamation mark in `!mockType`.
It wasn't obvious to me why is there "!" instead of usual "@".

I think changing it to "@" would align better with [TSDoc](https://github.com/microsoft/tsdoc) and be more familiar for people used to `@param` (I guess this is the most used JSDoc tag).

I've taken a quick look at [AST Viewer](https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgBIHsDOZkG8CwAUMsgPQBU5RJy5yAAgLboIDWAKgJ4AOKuokKCAhgAdMG4A3AGwBfaiXKkFcACaqoALmTYooAOYBuIrKA) with _"show internals"_ flag on. 

Instead of looking for [`"!mockType"` with `startsWith`](https://github.com/google/intermock/blob/master/src/lang/ts/intermock.ts#L284) one could look inside `propertySignature.jsDoc[number].tags` for `tag.tagName.text === "mockType"`.

Here's the gist with a proof of concept https://gist.github.com/hasparus/b1f78bffb783376a62dcd666de41da60

I you like the idea I'd gladly provide a pull request.

**Comment by ryanmcdermott** [comment]
It indeed is non standard. The issue was that I didn't want to parse `tag.tagName.text` for all possible tags, there was some issue with this when I explored it on ast-explorer back last year. If you can:
- Parse more tags than just `mockType` (That is the only one for now but in the future there will be more such as `mockRange`)
- And it passes all tests

Then I'm happy for you to open a PR! Thanks!!

**Comment by hasparus** [comment]
Looking at version (0.1.3) I assume I don't have to keep backwards compatibility and handle `!mockType`. Am I correct?

**Comment by ryanmcdermott** [comment]
Nope, you can get rid of backwards compatibility :) I didn't advertise Mock Docs as I'm calling them, because I still hadn't settled on syntactical questions. Thanks for asking, I'll just bump the minor version. Hopefully folks know this is still alpha.
